### ISSUE TITLE
Shairport metadata

### ISSUE THREAD

**Issue by GlebOlden** [idcrook/shairport-sync-mqtt-display#38]
Hello! Is there a way to get a separate image file from the shairport metadata feed? I use shairport to play music in my home using the Home Assistant. But the interface doesn't display metadata. I would be very grateful If you can help me.

Example of my interface:
![IMG_5543](https://user-images.githubusercontent.com/44943930/80551169-3fcd3180-89cb-11ea-8061-39f7730c666d.PNG)

**Comment by idcrook** [comment]
Hi. The apps with source code in this repo use the MQTT coverart feature in shairport-sync. There is a Unix pipe mechanism too. 

Contact the developer of the app you are using to ask them about metadata support. Also can refer to https://github.com/mikebrady/shairport-sync-metadata-reader

**Comment by GlebOlden** [comment]
Ok. Thank you!
