### ISSUE TITLE
Works with AirPlay 2!

### ISSUE THREAD

**Issue by kylejohnsonkj** [idcrook/shairport-sync-mqtt-display#43]
Thought I'd let you know that the flaschen-taschen setup works perfectly with the development branch of shairport-sync supporting AirPlay 2. Just switched to it today! 

Was a drop-in replacement, reused the same config file and everything. So that's pretty neat. 👍

**Comment by idcrook** [comment]
> Was a drop-in replacement, reused the same config file and everything. So that's pretty neat. 👍

`shairport-sync` and its MQTT support do all the heavy lifting, but that is great to hear! 🥇
