### ISSUE TITLE
Flask app won't start

### ISSUE THREAD

**Issue by nigelewan** [idcrook/shairport-sync-mqtt-display#49]
I receive the following error when attempting to launch `app.py`.

```
Traceback (most recent call last):
  File "/home/pi/projects/shairport-sync-mqtt-display/python-flask-socketio-server/app.py", line 15, in <module>
    from flask_socketio import SocketIO
  File "/home/pi/projects/shairport-sync-mqtt-display/python-flask-socketio-server/.venv/lib/python3.9/site-packages/flask_socketio/__init__.py", line 19, in <module>
    from flask import _request_ctx_stack, has_request_context, json as flask_json
ImportError: cannot import name '_request_ctx_stack' from 'flask' (/home/pi/projects/shairport-sync-mqtt-display/python-flask-socketio-server/.venv/lib/python3.9/site-packages/flask/__init__.py)
```

Any help (or pointers in the right direction) would be appreciated.

**Comment by idcrook** [comment]
Haven't looked further yet, but guessing this could be related to recent Flask 3.x (`3.0`) release getting pulled in.

Flask-2.3.2 is version I see in my working systems.

**Comment by idcrook** [comment]
I reproduced this issue.  And determined it is indeed the Flask version. I updated `requirements.txt` so that it doesn't pull in the 3.x for `flask` and it works as expected. I'll push a fix soon.

**Comment by idcrook** [comment]
To get this fix, you'll want to pull in the latest change, and delete the `.venv` directory.
then re-"install" as before (which will recreate the `.venv` directory with the updated `requirements.txt`
